Radio Control Layer (RCL): /home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/LRF.h File Reference
LRF.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
Data Structures
struct LRF_TOPsmImage
union LRF_ConfigWord
struct LRF_RegConfigList
struct LRF_ApplySettingsState
struct LRF_ConfigWord.region
struct LRF_ConfigWord.sparse
struct LRF_ConfigWord.masked
struct LRF_ConfigWord.segment
Macros
#define LRF_TxPower_Use_Min ((LRF_TxPowerTable_Index){.rawValue = -128})
#define LRF_TxPower_Use_Max ((LRF_TxPowerTable_Index){.rawValue = 125})
#define LRF_TxPower_Use_Raw ((LRF_TxPowerTable_Index){.rawValue = 126})
#define LRF_TxPower_None ((LRF_TxPowerTable_Index){.rawValue = 127})
#define LRF_SETTINGS_BUFFER_UNLIMITED 0x3FFF
#define LRF_RSSI_INVALID (127)
#define LRF_PhyFeatures_Default 0
#define LRF_NUM_CLK_ENA 2 /* Number of clock enable sets */
#define LRF_CLK_ENA_APP 0 /* Clock enable set to use for the application */
#define LRF_CLK_ENA_RCL 1 /* Clock enable set to use by the RCL */
#define __ERROR_Address_is_in_an_invalid_range_for_LRF_setup 0x00040000
#define _ADDRESS_REGION_BIT(_address)
#define LRF_SETTINGS_CLEAR(_startAddress, _numWords)
#define LRF_SETTINGS_16BIT_BLOCK(_startAddress, _numWords)
#define LRF_SETTINGS_16BIT_DUAL_ENTRY(_value0, _value1) (((_value0) & 0xFFFF) | (((_value1) & 0xFFFF) << 16))
#define LRF_SETTINGS_32BIT_BLOCK(_startAddress, _numWords)
#define LRF_SETTINGS_16BIT_SPARSE_BLOCK(_startAddress, _numWords)
#define LRF_SETTINGS_16BIT_SPARSE_ENTRY(_address, _value) (((((uintptr_t)(_address)) & 0xFFFF) << 16) | ((_value) & 0xFFFF))
#define LRF_SETTINGS_16BIT_MASKED_BLOCK(_startAddress, _numWords)
#define LRF_SETTINGS_16BIT_MASKED_ENTRY(_mask, _value) ((((_mask) & 0xFFFF) << 16) | ((_value) & 0xFFFF))
Enumerations
enum LRF_RadioState { RadioState_Down = 0, RadioState_ImagesLoaded, RadioState_Configured }
enum LRF_SetupResult {
SetupResult_Ok, SetupResult_Ok_Partial, SetupResult_ErrorImageLen, SetupResult_ErrorConfigLen,
SetupResult_ErrorElemLen, SetupResult_ErrorElemType, SetupResult_ErrorElemAddrAlign, SetupResult_ErrorParRange,
SetupResult_ErrorSwConfig
}
Setup operation result.
enum LRF_RegionOperation {
HW_Region_Clear = 0, HW_Write_16bit = 1, HW_Write_32bit = 2, HW_Write_16bit_sparse = 3,
SW_Region_Clear = 4, SW_Write_16bit = 5, SW_Write_32bit = 6, SW_Write_16bit_sparse = 7,
Par_Region_Clear = 8, Par_Reference_32bit = 9, Par_Write_32bit = 10, HW_Write_16bit_masked = 11,
LRF_RegionOperation_Skip = 254, LRF_RegionOperation_Invalid = 255
}
enum LRF_ApplySettingsBase { LRF_ApplySettings_NoBase = 0, LRF_ApplySettings_IncludeBase = 1 }
Functions
LRF_SetupResult LRF_setupRadio (const LRF_Config *lrfConfig, uint16_t phyFeatures, LRF_RadioState lrfState)
LRF_SetupResult LRF_loadImage (const LRF_TOPsmImage *image, uint32_t destinationAddress)
static void LRF_resetSettingsState (LRF_ApplySettingsState *state)
void LRF_initSettingsState (LRF_ApplySettingsState *state, LRF_ApplySettingsBase includeBase, uint16_t phyFeatures)
LRF_SetupResult LRF_applySettings (LRF_ConfigWord *config, LRF_ApplySettingsState *state, int32_t bufferAvailWords)
void LRF_enable (void)
void LRF_disable (void)
void LRF_powerDown (void)
void LRF_sendHardStop (void)
void LRF_sendGracefulStop (void)
void LRF_hardStop (void)
void LRF_waitForTopsmReady (void)
uint32_t LRF_prepareRxFifo (void)
uint32_t LRF_prepareTxFifo (void)
uint32_t LRF_peekRxFifo (int32_t offset)
uint32_t LRF_peekTxFifo (int32_t offset)
uint8_t * LRF_getTxFifoWrAddr (int32_t offset)
void LRF_skipTxFifoWords (uint32_t wordLength)
void LRF_discardRxFifoWords (uint32_t wordLength)
void LRF_readRxFifoWords (uint32_t *data32, uint32_t wordLength)
void LRF_writeTxFifoWords (const uint32_t *data32, uint32_t wordLength)
void LRF_setRxFifoEffSz (uint32_t maxSz)
void LRF_programFrequency (uint32_t frequency, bool tx)
uint32_t LRF_enableSynthRefsys (void)
void LRF_disableSynthRefsys (void)
void LRF_setClockEnable (uint16_t mask, uint8_t entryNumber)
void LRF_clearClockEnable (uint16_t mask, uint8_t entryNumber)
int8_t LRF_readRssi (void)
void LRF_setRawTxPower (uint32_t value, uint32_t temperatureCoefficient)
LRF_TxPowerTable_Entry LRF_getRawTxPower (void)
bool LRF_imagesNeedUpdate (const LRF_Config *lrfConfig)
LRF_TxPowerTable_Entry LRF_TxPowerTable_findValue (const LRF_TxPowerTable *table, LRF_TxPowerTable_Index powerLevel)
Search for settings corresponding to the highest tx power lower than specified value in the tx power table.
void LRF_rclEnableRadioClocks (void)
void LRF_rclDisableRadioClocks (void)
static void LRF_setAppClockEnable (uint16_t mask)
static void LRF_clearAppClockEnable (uint16_t mask)
Variables
uint32_t swParamList []
const size_t swParamListSz
Data Structure Documentation
LRF_TOPsmImage_s
struct LRF_TOPsmImage_s
Data Fields
uint32_t imageLen
uint32_t image[]
LRF_ConfigWord
union LRF_ConfigWord
Data Fields
struct LRF_ConfigWord region
uint32_t value32
uint16_t value16[2]
struct LRF_ConfigWord sparse
struct LRF_ConfigWord masked
struct LRF_ConfigWord segment
LRF_RegConfigList_s
struct LRF_RegConfigList_s
Data Fields
uint32_t numEntries
LRF_ConfigWord * entries[]
LRF_ApplySettingsState
struct LRF_ApplySettingsState
Data Fields
uint16_t phyFeatures
LRF_ApplySettingsBase includeBase
LRF_ConfigWord.region
struct LRF_ConfigWord.region
Data Fields
uint32_t lengthMinus1: 12
uint32_t type: 4
uint32_t startAddress: 16
LRF_ConfigWord.sparse
struct LRF_ConfigWord.sparse
Data Fields
uint16_t value16
uint16_t address
LRF_ConfigWord.masked
struct LRF_ConfigWord.masked
Data Fields
uint16_t value16
uint16_t mask16
LRF_ConfigWord.segment
struct LRF_ConfigWord.segment
Data Fields
uint32_t length: 14
uint32_t invertedFeatureMask: 1
uint32_t compoundSegment: 1
uint32_t featureMask: 16
Macro Definition Documentation
LRF_TxPower_Use_Min
#define LRF_TxPower_Use_Min ((LRF_TxPowerTable_Index){.rawValue = -128})
Special value given as a TX power to indicate that the lowest available TX power is requested
Referenced by LRF_TxPowerTable_findValue().
LRF_TxPower_Use_Max
#define LRF_TxPower_Use_Max ((LRF_TxPowerTable_Index){.rawValue = 125})
Special value given as a TX power to indicate that the highest available TX power is requested
Referenced by LRF_TxPowerTable_findValue().
LRF_TxPower_Use_Raw
#define LRF_TxPower_Use_Raw ((LRF_TxPowerTable_Index){.rawValue = 126})
Special value given as a TX power to indicate that a given raw TX power register setting should be used.
Referenced by LRF_getRawTxPower(), LRF_setRawTxPower(), and LRF_TxPowerTable_findValue().
LRF_TxPower_None
#define LRF_TxPower_None ((LRF_TxPowerTable_Index){.rawValue = 127})
Special value given as a TX power to indicate that a TX power should not be programmed; instead, use the register value written through settings or register write.
Referenced by LRF_programTxPower().
LRF_SETTINGS_BUFFER_UNLIMITED
#define LRF_SETTINGS_BUFFER_UNLIMITED 0x3FFF
Buffer available limit when no limit exists
Referenced by LRF_setupRadio().
LRF_RSSI_INVALID
#define LRF_RSSI_INVALID (127)
RSSI value indicating an invalid RSSI
Referenced by LRF_setupRadio(), RCL_BLE5_getRxRssi(), RCL_Handler_BLE5_initAdvScanInitStats(), RCL_Handler_BLE5_initConnStats(), RCL_Handler_BLE5_initGenericRxStats(), RCL_Handler_Generic_initRxStats(), RCL_Handler_Nesb_initStats(), and RCL_readRssi().
LRF_PhyFeatures_Default
#define LRF_PhyFeatures_Default 0
Referenced by RCL_Lite_config().
LRF_NUM_CLK_ENA
#define LRF_NUM_CLK_ENA 2 /* Number of clock enable sets */
Referenced by LRF_applyNewClockEnable(), LRF_clearClockEnable(), and LRF_setClockEnable().
LRF_CLK_ENA_APP
#define LRF_CLK_ENA_APP 0 /* Clock enable set to use for the application */
Referenced by LRF_clearAppClockEnable(), and LRF_setAppClockEnable().
LRF_CLK_ENA_RCL
#define LRF_CLK_ENA_RCL 1 /* Clock enable set to use by the RCL */
Referenced by LRF_rclDisableRadioClocks(), LRF_rclEnableRadioClocks(), RCL_Handler_Adc_Noise_configureS2R(), RCL_Handler_Adc_Noise_powerDown(), RCL_Handler_BLE_CS_configureS2R(), and RCL_Handler_BLE_CS_preprocessCommand().
__ERROR_Address_is_in_an_invalid_range_for_LRF_setup
#define __ERROR_Address_is_in_an_invalid_range_for_LRF_setup 0x00040000
_ADDRESS_REGION_BIT
#define _ADDRESS_REGION_BIT (_address)
Value:
((((((uintptr_t)(_address)) >= (LRF_BASE_ADDR)) &&                  \
       ((uintptr_t)(_address)) < ((LRF_BASE_ADDR) + 0x10000)) ? 0 :     \
      ((((uintptr_t)(_address)) >= (PBE_RAM_BASE_ADDR)) &&              \
        (((uintptr_t)(_address)) < ((PBE_RAM_BASE_ADDR) + 0x10000)) ?   \
       1 :                                                              \
       (((((uintptr_t)(_address)) >= 0) &&                              \
        (((uintptr_t)(_address)) < 0x10000)) ?                          \
       2 :                                                              \
       (__ERROR_Address_is_in_an_invalid_range_for_LRF_setup)))) << 14)
LRF_SETTINGS_CLEAR
#define LRF_SETTINGS_CLEAR (_startAddress, _numWords)
Value:
((((_numWords) - 1) & 0x0FFF) |                                     \
     _ADDRESS_REGION_BIT(_startAddress) |                               \
     ((((uintptr_t)(_startAddress)) & 0xFFFF) << 16))
LRF_SETTINGS_16BIT_BLOCK
#define LRF_SETTINGS_16BIT_BLOCK (_startAddress, _numWords)
Value:
((((_numWords) - 1) & 0x0FFF) |                                     \
    _ADDRESS_REGION_BIT(_startAddress) | (1 << 12) |                    \
     ((((uintptr_t)(_startAddress)) & 0xFFFF) << 16))
LRF_SETTINGS_16BIT_DUAL_ENTRY
#define LRF_SETTINGS_16BIT_DUAL_ENTRY (_value0, _value1) (((_value0) & 0xFFFF) | (((_value1) & 0xFFFF) << 16))
LRF_SETTINGS_32BIT_BLOCK
#define LRF_SETTINGS_32BIT_BLOCK (_startAddress, _numWords)
Value:
((((_numWords) - 1) & 0x0FFF) |                                     \
     _ADDRESS_REGION_BIT(_startAddress) | (2 << 12) |                   \
     ((((uintptr_t)(_startAddress)) & 0xFFFF) << 16))
LRF_SETTINGS_16BIT_SPARSE_BLOCK
#define LRF_SETTINGS_16BIT_SPARSE_BLOCK (_startAddress, _numWords)
Value:
((((_numWords) - 1) & 0x0FFF) |                                     \
     _ADDRESS_REGION_BIT(_startAddress) | (3 << 12))                    \
LRF_SETTINGS_16BIT_SPARSE_ENTRY
#define LRF_SETTINGS_16BIT_SPARSE_ENTRY (_address, _value) (((((uintptr_t)(_address)) & 0xFFFF) << 16) | ((_value) & 0xFFFF))
LRF_SETTINGS_16BIT_MASKED_BLOCK
#define LRF_SETTINGS_16BIT_MASKED_BLOCK (_startAddress, _numWords)
Value:
((((_numWords) - 1) & 0x0FFF) | (11 << 12) |                        \
     ((((uintptr_t)(_startAddress)) & 0xFFFF) << 16))
LRF_SETTINGS_16BIT_MASKED_ENTRY
#define LRF_SETTINGS_16BIT_MASKED_ENTRY (_mask, _value) ((((_mask) & 0xFFFF) << 16) | ((_value) & 0xFFFF))
Enumeration Type Documentation
LRF_RadioState
enum LRF_RadioState
Enumerator
RadioState_Down
RadioState_ImagesLoaded
RadioState_Configured
LRF_SetupResult
enum LRF_SetupResult
Setup operation result.
Enumerator
SetupResult_Ok
Setup was successful
SetupResult_Ok_Partial
Setup was successful so far, need rest of buffer
SetupResult_ErrorImageLen
An image was too long
SetupResult_ErrorConfigLen
A register configuration table was too long
SetupResult_ErrorElemLen
A register configuration element exceeded the table length
SetupResult_ErrorElemType
A register configuration element had invalid type
SetupResult_ErrorElemAddrAlign
A register configuration element had unsupported address alignment
SetupResult_ErrorParRange
A register parameter element was outside the allowed range
SetupResult_ErrorSwConfig
The swConfig field was NULL
LRF_RegionOperation
enum LRF_RegionOperation
Enumerator
HW_Region_Clear
HW_Write_16bit
HW_Write_32bit
HW_Write_16bit_sparse
SW_Region_Clear
SW_Write_16bit
SW_Write_32bit
SW_Write_16bit_sparse
Par_Region_Clear
Par_Reference_32bit
Par_Write_32bit
HW_Write_16bit_masked
LRF_RegionOperation_Skip
LRF_RegionOperation_Invalid
LRF_ApplySettingsBase
enum LRF_ApplySettingsBase
Enumerator
LRF_ApplySettings_NoBase
LRF_ApplySettings_IncludeBase
Function Documentation
LRF_setupRadio()
LRF_SetupResult LRF_setupRadio (const LRF_Config * lrfConfig, uint16_t phyFeatures, LRF_RadioState lrfState)
References LRF_applySettings(), LRF_ApplySettings_IncludeBase, LRF_ApplySettings_NoBase, LRF_applyTrim(), LRF_initSettingsState(), LRF_loadImage(), LRF_RSSI_INVALID, LRF_setTemperatureTrim(), LRF_SETTINGS_BUFFER_UNLIMITED, LRF_updateTrim(), lrfPhyState, LRF_Config::mceImage, LRF_Config::pbeImage, RadioState_Configured, RadioState_ImagesLoaded, LRF_Config::regConfigList, LRF_Config::rfeImage, SetupResult_ErrorSwConfig, SetupResult_Ok, LRF_SwParam::swConfig, swParamList, and LRF_SwParam::trimDef.
Referenced by RCL_Lite_configSetPhyFeatures(), RCL_Lite_setPhyFeatures(), and rclCommandHwi().
LRF_loadImage()
LRF_SetupResult LRF_loadImage (const LRF_TOPsmImage * image, uint32_t destinationAddress)
References SetupResult_ErrorImageLen, SetupResult_Ok, and TOPSM_RAM_SZ.
Referenced by LRF_setupRadio().
LRF_resetSettingsState()
static void LRF_resetSettingsState (LRF_ApplySettingsState * state) inline static
References LRF_applySettings(), LRF_clearClockEnable(), LRF_disable(), LRF_disableSynthRefsys(), LRF_discardRxFifoWords(), LRF_enable(), LRF_enableSynthRefsys(), LRF_getRawTxPower(), LRF_getTxFifoWrAddr(), LRF_hardStop(), LRF_imagesNeedUpdate(), LRF_initSettingsState(), LRF_peekRxFifo(), LRF_peekTxFifo(), LRF_powerDown(), LRF_prepareRxFifo(), LRF_prepareTxFifo(), LRF_programFrequency(), LRF_rclDisableRadioClocks(), LRF_rclEnableRadioClocks(), LRF_readRssi(), LRF_readRxFifoWords(), LRF_sendGracefulStop(), LRF_sendHardStop(), LRF_setClockEnable(), LRF_setRawTxPower(), LRF_setRxFifoEffSz(), LRF_skipTxFifoWords(), LRF_TxPowerTable_findValue(), LRF_waitForTopsmReady(), and LRF_writeTxFifoWords().
Referenced by LRF_initSettingsState().
LRF_initSettingsState()
void LRF_initSettingsState (LRF_ApplySettingsState * state, LRF_ApplySettingsBase includeBase, uint16_t phyFeatures)
References LRF_ApplySettingsState::includeBase, LRF_resetSettingsState(), and LRF_ApplySettingsState::phyFeatures.
Referenced by LRF_resetSettingsState(), and LRF_setupRadio().
LRF_applySettings()
LRF_SetupResult LRF_applySettings (LRF_ConfigWord * config, LRF_ApplySettingsState * state, int32_t bufferAvailWords)
References HW_Region_Clear, HW_Write_16bit, HW_Write_16bit_masked, HW_Write_16bit_sparse, HW_Write_32bit, LRF_ApplySettingsState::includeBase, LRF_BASE_ADDR, LRF_RegionOperation_Invalid, LRF_RegionOperation_Skip, LRF_ConfigWord::masked, MAX_REG_CONFIG_LEN, Par_Reference_32bit, Par_Region_Clear, Par_Write_32bit, PBE_RAM_BASE_ADDR, LRF_ApplySettingsState::phyFeatures, RCL_Debug_assert, LRF_ConfigWord::region, LRF_ConfigWord::segment, SetupResult_ErrorConfigLen, SetupResult_ErrorElemAddrAlign, SetupResult_ErrorElemLen, SetupResult_ErrorElemType, SetupResult_ErrorParRange, SetupResult_Ok, SetupResult_Ok_Partial, LRF_ConfigWord::sparse, SW_Region_Clear, SW_Write_16bit, SW_Write_16bit_sparse, SW_Write_32bit, swParamList, swParamListSz, LRF_ConfigWord::value16, and LRF_ConfigWord::value32.
Referenced by LRF_resetSettingsState(), and LRF_setupRadio().
LRF_enable()
void LRF_enable (void)
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_BLE_CS(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_FsOff(), RCL_Handler_Generic_PbeOperation(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Generic_TxTest(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_disable()
void LRF_disable (void)
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_BLE_CS(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_FsOff(), RCL_Handler_Generic_PbeOperation(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Generic_TxTest(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_powerDown()
void LRF_powerDown (void)
Referenced by LRF_resetSettingsState().
LRF_sendHardStop()
void LRF_sendHardStop (void)
Referenced by LRF_resetSettingsState(), RCL_Lite_Command_stop(), and rclStop().
LRF_sendGracefulStop()
void LRF_sendGracefulStop (void)
Referenced by LRF_resetSettingsState(), RCL_Lite_Command_stop(), and rclStop().
LRF_hardStop()
void LRF_hardStop (void)
Referenced by LRF_resetSettingsState(), RCL_Lite_CommandHwi(), and rclCommandHwi().
LRF_waitForTopsmReady()
void LRF_waitForTopsmReady (void)
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_BLE_CS(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_FsOff(), RCL_Handler_Generic_PbeOperation(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Generic_TxTest(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_prepareRxFifo()
uint32_t LRF_prepareRxFifo (void)
References rxFifoDeallocated.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Rx(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_prepareTxFifo()
uint32_t LRF_prepareTxFifo (void)
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_peekRxFifo()
uint32_t LRF_peekRxFifo (int32_t offset)
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Rx(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_peekTxFifo()
uint32_t LRF_peekTxFifo (int32_t offset)
Referenced by LRF_resetSettingsState().
LRF_getTxFifoWrAddr()
uint8_t* LRF_getTxFifoWrAddr (int32_t offset)
References TXF_UNWRAPPED_BASE_ADDR.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_getAuxPtr(), RCL_Handler_BLE5_scan_init(), and RCL_Handler_BLE5_updateTxBuffers().
LRF_skipTxFifoWords()
void LRF_skipTxFifoWords (uint32_t wordLength)
References LRF_writeFifoPtr().
Referenced by LRF_resetSettingsState(), and RCL_Handler_BLE5_updateTxBuffers().
LRF_discardRxFifoWords()
void LRF_discardRxFifoWords (uint32_t wordLength)
References LRF_writeFifoPtrs(), and rxFifoDeallocated.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_genericRx(), RCL_Handler_Generic_Rx(), and RCL_Handler_Nesb_Prx().
LRF_readRxFifoWords()
void LRF_readRxFifoWords (uint32_t * data32, uint32_t wordLength)
References LRF_writeFifoPtr(), RXF_UNWRAPPED_BASE_ADDR, and rxFifoDeallocated.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Rx(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_writeTxFifoWords()
void LRF_writeTxFifoWords (const uint32_t * data32, uint32_t wordLength)
References LRF_writeFifoPtr(), and TXF_UNWRAPPED_BASE_ADDR.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_updateTxBuffers(), RCL_Handler_Generic_TxRepeat(), and RCL_Handler_Generic_updateTxBuffers().
LRF_setRxFifoEffSz()
void LRF_setRxFifoEffSz (uint32_t maxSz)
References LRF_writeFifoPtr(), and rxFifoDeallocated.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_updateRxCurBufferAndFifo(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_updateRxCurBufferAndFifo(), and RCL_Handler_Nesb_Prx().
LRF_programFrequency()
void LRF_programFrequency (uint32_t frequency, bool tx)
References LRF_findCalM(), LRF_findFoff(), LRF_findPllMBase(), LRF_programCMixN(), LRF_programPQ(), LRF_programShape(), LRF_scaleFreqWithHFXTOffset(), LRF_SwConfig::modFrequencyDeviation, LRF_SwConfig::rxFrequencyOffset, LRF_SwConfig::rxIntFrequency, LRF_SwParam::swConfig, swParamList, LRF_SwConfig::txFrequencyOffset, and LRF_SwConfig::txShape.
Referenced by LRF_resetSettingsState(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Generic_TxTest(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_enableSynthRefsys()
uint32_t LRF_enableSynthRefsys (void)
References LRF_REFSYS_ENABLE_TIME, and RCL_Scheduler_getCurrentTime().
Referenced by LRF_resetSettingsState(), RCL_Handler_ADC_Noise_getNoise(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_BLE_CS(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_Rx(), RCL_Handler_Generic_Tx(), RCL_Handler_Generic_TxRepeat(), RCL_Handler_Generic_TxTest(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
LRF_disableSynthRefsys()
void LRF_disableSynthRefsys (void)
Referenced by LRF_resetSettingsState(), RCL_Handler_ADC_Noise_getNoise(), RCL_Handler_Adc_Noise_powerDown(), RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_dtmTx(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_genericTx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Ble5_txTest(), RCL_Handler_BLE_CS(), and RCL_Handler_Generic_setSynthPowerState().
LRF_setClockEnable()
void LRF_setClockEnable (uint16_t mask, uint8_t entryNumber)
References LRF_applyNewClockEnable(), LRF_NUM_CLK_ENA, and lrfPhyState.
Referenced by LRF_rclEnableRadioClocks(), LRF_resetSettingsState(), LRF_setAppClockEnable(), RCL_Handler_Adc_Noise_configureS2R(), RCL_Handler_BLE_CS_configureS2R(), and RCL_Handler_BLE_CS_preprocessCommand().
LRF_clearClockEnable()
void LRF_clearClockEnable (uint16_t mask, uint8_t entryNumber)
References LRF_applyNewClockEnable(), LRF_NUM_CLK_ENA, and lrfPhyState.
Referenced by LRF_clearAppClockEnable(), LRF_rclDisableRadioClocks(), LRF_resetSettingsState(), and RCL_Handler_Adc_Noise_powerDown().
LRF_readRssi()
int8_t LRF_readRssi (void)
Referenced by LRF_resetSettingsState(), RCL_Lite_readRssi(), and RCL_readRssi().
LRF_setRawTxPower()
void LRF_setRawTxPower (uint32_t value, uint32_t temperatureCoefficient)
References LRF_TxPower_Use_Raw, and lrfPhyState.
Referenced by LRF_resetSettingsState(), and RCL_Command_setRawTxPower().
LRF_getRawTxPower()
LRF_TxPowerTable_Entry LRF_getRawTxPower (void)
References LRF_TxPower_Use_Raw, LRF_TxPowerEntry_INVALID_VALUE, and lrfPhyState.
Referenced by LRF_resetSettingsState(), and LRF_TxPowerTable_findValue().
LRF_imagesNeedUpdate()
bool LRF_imagesNeedUpdate (const LRF_Config * lrfConfig)
References lrfPhyState, LRF_Config::mceImage, LRF_Config::pbeImage, and LRF_Config::rfeImage.
Referenced by LRF_resetSettingsState(), and rclSchedulerHwi().
LRF_TxPowerTable_findValue()
LRF_TxPowerTable_Entry LRF_TxPowerTable_findValue (const LRF_TxPowerTable * table, LRF_TxPowerTable_Index powerLevel)
Search for settings corresponding to the highest tx power lower than specified value in the tx power table.
Parameters
table pointer to the tx power table to be searched
powerLevel maximum allowed power level
Returns
Settings corresponding to a power level equal to or lower than requested or LRF_TxPowerTable_INVALID_VALUE if no valid setting was found.
References LRF_getRawTxPower(), LRF_TxPower_Use_Max, LRF_TxPower_Use_Min, LRF_TxPower_Use_Raw, LRF_TxPowerEntry_INVALID_VALUE, LRF_TxPowerTable::numEntries, LRF_TxPowerTable_Entry::power, LRF_TxPowerTable::powerTable, and LRF_TxPowerTable_Index::rawValue.
Referenced by LRF_programTxPower(), and LRF_resetSettingsState().
LRF_rclEnableRadioClocks()
void LRF_rclEnableRadioClocks (void)
References LRF_CLK_ENA_RCL, and LRF_setClockEnable().
Referenced by LRF_resetSettingsState(), RCL_Lite_configSetPhyFeatures(), RCL_open(), and rclPowerNotify().
LRF_rclDisableRadioClocks()
void LRF_rclDisableRadioClocks (void)
References LRF_clearClockEnable(), and LRF_CLK_ENA_RCL.
Referenced by LRF_resetSettingsState(), and RCL_close().
LRF_setAppClockEnable()
static void LRF_setAppClockEnable (uint16_t mask) inline static
References LRF_CLK_ENA_APP, and LRF_setClockEnable().
Referenced by RCL_AdcNoise_get_samples_blocking(), and RCL_AdcNoise_get_samples_callback().
LRF_clearAppClockEnable()
static void LRF_clearAppClockEnable (uint16_t mask) inline static
References LRF_clearClockEnable(), LRF_CLK_ENA_APP, swParamList, and swParamListSz.
Referenced by adcNoiseCallback(), and RCL_AdcNoise_get_samples_blocking().
Variable Documentation
swParamList
uint32_t swParamList[]
Referenced by LRF_applySettings(), LRF_clearAppClockEnable(), LRF_programFrequency(), LRF_programTxPower(), and LRF_setupRadio().
swParamListSz
const size_t swParamListSz
Referenced by LRF_applySettings(), and LRF_clearAppClockEnable().