Radio Control Layer (RCL): /home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/LRF.c File Reference
LRF.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/RCL_Debug.h>
#include <ti/drivers/rcl/LRF.h>
#include <ti/log/Log.h>
Functions
LRF_SetupResult LRF_loadImage (const LRF_TOPsmImage *image, uint32_t destinationAddress)
void LRF_initSettingsState (LRF_ApplySettingsState *state, LRF_ApplySettingsBase includeBase, uint16_t phyFeatures)
LRF_SetupResult LRF_applySettings (LRF_ConfigWord *config, LRF_ApplySettingsState *state, int32_t bufferAvailWords)
LRF_TxPowerTable_Entry LRF_TxPowerTable_findValue (const LRF_TxPowerTable *table, LRF_TxPowerTable_Index powerLevel)
Search for settings corresponding to the highest tx power lower than specified value in the tx power table.
Function Documentation
LRF_loadImage()
LRF_SetupResult LRF_loadImage (const LRF_TOPsmImage * image, uint32_t destinationAddress)
References SetupResult_ErrorImageLen, SetupResult_Ok, and TOPSM_RAM_SZ.
Referenced by LRF_setupRadio().
LRF_initSettingsState()
void LRF_initSettingsState (LRF_ApplySettingsState * state, LRF_ApplySettingsBase includeBase, uint16_t phyFeatures)
References LRF_ApplySettingsState::includeBase, LRF_resetSettingsState(), and LRF_ApplySettingsState::phyFeatures.
Referenced by LRF_resetSettingsState(), and LRF_setupRadio().
LRF_applySettings()
LRF_SetupResult LRF_applySettings (LRF_ConfigWord * config, LRF_ApplySettingsState * state, int32_t bufferAvailWords)
References HW_Region_Clear, HW_Write_16bit, HW_Write_16bit_masked, HW_Write_16bit_sparse, HW_Write_32bit, LRF_ApplySettingsState::includeBase, LRF_BASE_ADDR, LRF_RegionOperation_Invalid, LRF_RegionOperation_Skip, LRF_ConfigWord::masked, MAX_REG_CONFIG_LEN, Par_Reference_32bit, Par_Region_Clear, Par_Write_32bit, PBE_RAM_BASE_ADDR, LRF_ApplySettingsState::phyFeatures, RCL_Debug_assert, LRF_ConfigWord::region, LRF_ConfigWord::segment, SetupResult_ErrorConfigLen, SetupResult_ErrorElemAddrAlign, SetupResult_ErrorElemLen, SetupResult_ErrorElemType, SetupResult_ErrorParRange, SetupResult_Ok, SetupResult_Ok_Partial, LRF_ConfigWord::sparse, SW_Region_Clear, SW_Write_16bit, SW_Write_16bit_sparse, SW_Write_32bit, swParamList, swParamListSz, LRF_ConfigWord::value16, and LRF_ConfigWord::value32.
Referenced by LRF_resetSettingsState(), and LRF_setupRadio().
LRF_TxPowerTable_findValue()
LRF_TxPowerTable_Entry LRF_TxPowerTable_findValue (const LRF_TxPowerTable * table, LRF_TxPowerTable_Index powerLevel)
Search for settings corresponding to the highest tx power lower than specified value in the tx power table.
Parameters
table pointer to the tx power table to be searched
powerLevel maximum allowed power level
Returns
Settings corresponding to a power level equal to or lower than requested or LRF_TxPowerTable_INVALID_VALUE if no valid setting was found.
References LRF_getRawTxPower(), LRF_TxPower_Use_Max, LRF_TxPower_Use_Min, LRF_TxPower_Use_Raw, LRF_TxPowerEntry_INVALID_VALUE, LRF_TxPowerTable::numEntries, LRF_TxPowerTable_Entry::power, LRF_TxPowerTable::powerTable, and LRF_TxPowerTable_Index::rawValue.
Referenced by LRF_programTxPower(), and LRF_resetSettingsState().