Radio Control Layer (RCL): ti/drivers/rcl/wrappers/RCL_AdcNoise.c File Reference
RCL_AdcNoise.c File Reference
#include <stdint.h>
#include <string.h>
#include <ti/devices/DeviceFamily.h>
#include <ti/drivers/rcl/RCL.h>
#include <ti/drivers/rcl/commands/adc_noise.h>
#include <ti/boards/cc23x0/rcl_settings_adc_noise.h>
Macros
#define PBE_COMMON_RAM_REGISTER_END_OFFSET 32UL
#define RCL_CLIENT_ADDR (BUF_RAM_BASE_ADDR + PBE_COMMON_RAM_REGISTER_END_OFFSET)
#define RCL_ADC_NOISE_CMD_ADDR (RCL_CLIENT_ADDR + sizeof(RCL_Client))
#define CALLBACK_ADDR (RCL_ADC_NOISE_CMD_ADDR + sizeof(RCL_CmdAdcNoiseGet))
#define RCL_CLIENT_PTR ((RCL_Client*)RCL_CLIENT_ADDR)
#define RCL_ADC_NOISE_CMD_PTR ((RCL_CmdAdcNoiseGet*)RCL_ADC_NOISE_CMD_ADDR)
#define CALLBACK_PTR ((applicationCallback_t*)CALLBACK_ADDR)
#define STATUS_SUCCESS 0
#define STATUS_ERROR -1
#define RCL_STATUS_TO_WRAPPER_STATUS(x) ((x) == RCL_CommandStatus_Finished ? STATUS_SUCCESS : STATUS_ERROR)
Typedefs
typedef void(* applicationCallback_t) (uint32_t *buffer, uint32_t numWords, int_fast16_t status)
Functions
static void adcNoiseCallback (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEvents)
int_fast16_t RCL_AdcNoise_get_samples_blocking (uint32_t *buffer, uint32_t numWords)
int_fast16_t RCL_AdcNoise_get_samples_callback (uint32_t *buffer, uint32_t numWords, applicationCallback_t callback)
Macro Definition Documentation
PBE_COMMON_RAM_REGISTER_END_OFFSET
#define PBE_COMMON_RAM_REGISTER_END_OFFSET 32UL
RCL_CLIENT_ADDR
#define RCL_CLIENT_ADDR (BUF_RAM_BASE_ADDR + PBE_COMMON_RAM_REGISTER_END_OFFSET)
RCL_ADC_NOISE_CMD_ADDR
#define RCL_ADC_NOISE_CMD_ADDR (RCL_CLIENT_ADDR + sizeof(RCL_Client))
CALLBACK_ADDR
#define CALLBACK_ADDR (RCL_ADC_NOISE_CMD_ADDR + sizeof(RCL_CmdAdcNoiseGet))
RCL_CLIENT_PTR
#define RCL_CLIENT_PTR ((RCL_Client*)RCL_CLIENT_ADDR)
Referenced by RCL_AdcNoise_get_samples_blocking(), and RCL_AdcNoise_get_samples_callback().
RCL_ADC_NOISE_CMD_PTR
#define RCL_ADC_NOISE_CMD_PTR ((RCL_CmdAdcNoiseGet*)RCL_ADC_NOISE_CMD_ADDR)
Referenced by RCL_AdcNoise_get_samples_blocking(), and RCL_AdcNoise_get_samples_callback().
CALLBACK_PTR
#define CALLBACK_PTR ((applicationCallback_t*)CALLBACK_ADDR)
Referenced by adcNoiseCallback(), and RCL_AdcNoise_get_samples_callback().
STATUS_SUCCESS
#define STATUS_SUCCESS 0
STATUS_ERROR
#define STATUS_ERROR -1
RCL_STATUS_TO_WRAPPER_STATUS
#define RCL_STATUS_TO_WRAPPER_STATUS (x) ((x) == RCL_CommandStatus_Finished ? STATUS_SUCCESS : STATUS_ERROR)
Referenced by adcNoiseCallback(), RCL_AdcNoise_get_samples_blocking(), and RCL_AdcNoise_get_samples_callback().
Typedef Documentation
applicationCallback_t
typedef void(* applicationCallback_t) (uint32_t *buffer, uint32_t numWords, int_fast16_t status)
Function Documentation
adcNoiseCallback()
static void adcNoiseCallback (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEvents) static
References CALLBACK_PTR, hal_power_release_constraint(), LRF_clearAppClockEnable(), RCL_close(), and RCL_STATUS_TO_WRAPPER_STATUS.
Referenced by RCL_AdcNoise_get_samples_callback().
RCL_AdcNoise_get_samples_blocking()
int_fast16_t RCL_AdcNoise_get_samples_blocking (uint32_t * buffer, uint32_t numWords)
References hal_power_release_constraint(), hal_power_set_constraint(), LRF_clearAppClockEnable(), LRF_setAppClockEnable(), RCL_ADC_NOISE_CMD_PTR, RCL_CLIENT_PTR, RCL_close(), RCL_CmdAdcNoiseGet_Default, RCL_Command_pend(), RCL_Command_submit(), RCL_CommandStatus_Finished, RCL_init(), RCL_open(), and RCL_STATUS_TO_WRAPPER_STATUS.
RCL_AdcNoise_get_samples_callback()
int_fast16_t RCL_AdcNoise_get_samples_callback (uint32_t * buffer, uint32_t numWords, applicationCallback_t callback)
References adcNoiseCallback(), CALLBACK_PTR, hal_power_set_constraint(), LRF_setAppClockEnable(), RCL_ADC_NOISE_CMD_PTR, RCL_CLIENT_PTR, RCL_CmdAdcNoiseGet_Default, RCL_Command_submit(), RCL_EventLastCmdDone, RCL_init(), RCL_open(), and RCL_STATUS_TO_WRAPPER_STATUS.