Radio Control Layer (RCL): /home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Tracer.h File Reference
RCL_Tracer.h File Reference
Functions
void __attribute__ ((weak)) RCL_Tracer_enable(void)
Function Documentation
__attribute__()
void __attribute__ ((weak))
References RCL_SchedulerState::currCmd, RCL_SchedulerState::gracefulStopInfo, RCL_SchedulerState::hardStopInfo, RCL_SchedulerState::nextWantsStop, phyHook(), policyHook(), RCL_ConflictPolicy_AlwaysInterrupt, RCL_ConflictPolicy_NeverInterrupt, RCL_ConflictPolicy_Polite, RCL_Schedule_Now, RCL_Scheduler_getCurrentTime(), RCL_Scheduler_isLater(), RCL_SCHEDULER_MARGIN_LOAD, RCL_Scheduler_setSchedStopTime(), RCL_SchedulerStopReason_Scheduling, RCL_StopType_DescheduleOnly, RCL_StopType_Graceful, RCL_StopType_Hard, RCL_StopType_None, rclSchedulerState, rclStop(), and scheduleHook().
Referenced by RCL_close().