Radio Control Layer (RCL): /home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Buffer.c File Reference
RCL_Buffer.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/RCL_Scheduler.h>
#include <ti/drivers/rcl/RCL_Buffer.h>
#include <ti/drivers/rcl/RCL_Debug.h>
#include <ti/log/Log.h>
#include <ti/devices/DeviceFamily.h>
Functions
static bool RxEntry_isAtEnd (RCL_MultiBuffer *multiBuffer, uint16_t curIndex)
static void List_consumeAndStore (List_List *list, List_List *consumedBuffers)
void RCL_TxBuffer_put (List_List *list, RCL_Buffer_TxBuffer *elem)
Function to atomically put an elem onto the end of a Tx Buffer list.
uint8_t * RCL_TxBuffer_init (RCL_Buffer_TxBuffer *buffer, uint32_t numPad, uint32_t hdrLen, uint32_t dataLen)
Function to initialize a TX buffer entry for use by RCL.
void RCL_MultiBuffer_clear (RCL_MultiBuffer *buffer)
Function to clear a multi buffer entry for re-use by RCL.
void RCL_MultiBuffer_init (RCL_MultiBuffer *buffer, size_t size)
Function to initialize a multi buffer entry for use by RCL.
void RCL_MultiBuffer_put (List_List *list, RCL_MultiBuffer *elem)
Function to atomically put an elem onto the end of a multi buffer list.
RCL_Buffer_DataEntry * RCL_MultiBuffer_RxEntry_get (List_List *list, List_List *consumedBuffers)
Function to get the first entry in a MultiBuffer list.
bool RCL_MultiBuffer_RxEntry_isEmpty (List_List *list)
Function to check if the MultiBuffer List is out of entries.
void RCL_MultiBuffer_ListInfo_init (RCL_MultiBuffer_ListInfo *listInfo, List_List *list)
Function to initialize information for traversing a multi buffer list.
RCL_Buffer_DataEntry * RCL_MultiBuffer_RxEntry_next (RCL_MultiBuffer_ListInfo *listInfo)
Function to return the next entry in a list of multi buffers.
bool RCL_MultiBuffer_RxEntry_isLast (RCL_MultiBuffer_ListInfo *listInfo)
Function to check a traversed entry was the last one.
void RCL_MultiBuffer_RxEntry_consume (RCL_MultiBuffer_ListInfo *listInfo, List_List *consumedBuffers)
RCL_MultiBuffer * RCL_MultiBuffer_findFirstWritableBuffer (RCL_MultiBuffer *head)
Find the first writable buffer in a list of MultiBuffers.
RCL_MultiBuffer * RCL_MultiBuffer_getBuffer (RCL_MultiBuffer *curBuffer, uint32_t minLength)
Returns a buffer with at least minLength bytes remaining capacity.
uint32_t RCL_MultiBuffer_findAvailableRxSpace (const RCL_MultiBuffer *curBuffer)
Find the minumum number of bytes that can be stored in available MultiBuffers.
Function Documentation
RxEntry_isAtEnd()
static bool RxEntry_isAtEnd (RCL_MultiBuffer * multiBuffer, uint16_t curIndex) static
References RCL_BufferStateFinished.
Referenced by RCL_MultiBuffer_RxEntry_isEmpty(), and RCL_MultiBuffer_RxEntry_isLast().
List_consumeAndStore()
static void List_consumeAndStore (List_List * list, List_List * consumedBuffers) static
Referenced by RCL_MultiBuffer_RxEntry_consume(), and RCL_MultiBuffer_RxEntry_get().
RCL_MultiBuffer_RxEntry_consume()
void RCL_MultiBuffer_RxEntry_consume (RCL_MultiBuffer_ListInfo * listInfo, List_List * consumedBuffers)
References List_consumeAndStore(), RCL_Debug_assert, and RCL_MultiBuffer_head().