Radio Control Layer (RCL): ti/drivers/rcl/handlers/adc_noise.c File Reference
adc_noise.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/RCL_Types.h>
#include <ti/drivers/rcl/RCL_Scheduler.h>
#include <ti/drivers/rcl/commands/adc_noise.h>
#include <ti/log/Log.h>
#include <ti/devices/DeviceFamily.h>
Macros
#define ADC_NOISE_SAMPLE_MEM (PBE_RAM_BASE_ADDR)
#define ADC_NOISE_SAMPLE_PTR ((uint32_t *)ADC_NOISE_SAMPLE_MEM)
#define ADC_NOISE_SAMPLE_MEM_S2R_START 2048
Functions
static void RCL_Handler_Adc_Noise_configureS2R (uint32_t numWords)
static void RCL_Handler_Adc_Noise_powerUp (void)
static void RCL_Handler_Adc_Noise_powerDown (void)
RCL_Events RCL_Handler_ADC_Noise_getNoise (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
Variables
struct {
uint8_t synthRefsys:1
uint8_t powerUp:1
uint8_t s2rConversion:1
} adcNoiseHandlerState
Macro Definition Documentation
ADC_NOISE_SAMPLE_MEM
#define ADC_NOISE_SAMPLE_MEM (PBE_RAM_BASE_ADDR)
ADC_NOISE_SAMPLE_PTR
#define ADC_NOISE_SAMPLE_PTR ((uint32_t *)ADC_NOISE_SAMPLE_MEM)
Referenced by RCL_Handler_ADC_Noise_getNoise().
ADC_NOISE_SAMPLE_MEM_S2R_START
#define ADC_NOISE_SAMPLE_MEM_S2R_START 2048
Referenced by RCL_Handler_Adc_Noise_configureS2R().
Function Documentation
RCL_Handler_Adc_Noise_configureS2R()
static void RCL_Handler_Adc_Noise_configureS2R (uint32_t numWords) static
References ADC_NOISE_SAMPLE_MEM_S2R_START, LRF_CLK_ENA_RCL, and LRF_setClockEnable().
Referenced by RCL_Handler_ADC_Noise_getNoise().
RCL_Handler_Adc_Noise_powerUp()
static void RCL_Handler_Adc_Noise_powerUp (void) static
Referenced by RCL_Handler_ADC_Noise_getNoise().
RCL_Handler_Adc_Noise_powerDown()
static void RCL_Handler_Adc_Noise_powerDown (void) static
References LRF_clearClockEnable(), LRF_CLK_ENA_RCL, and LRF_disableSynthRefsys().
Referenced by RCL_Handler_ADC_Noise_getNoise().
RCL_Handler_ADC_Noise_getNoise()
RCL_Events RCL_Handler_ADC_Noise_getNoise (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References ADC_NOISE_SAMPLE_PTR, adcNoiseHandlerState, LRF_disableSynthRefsys(), LRF_enableSynthRefsys(), RCL_ADC_NOISE_MAX_NUM_WORDS, RCL_CommandStatus_Active, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Finished, RCL_Handler_Adc_Noise_configureS2R(), RCL_Handler_Adc_Noise_powerDown(), RCL_Handler_Adc_Noise_powerUp(), RCL_Scheduler_getCurrentTime(), RCL_Scheduler_setNewStartAbsTime(), and RCL_Scheduler_setStartStopTimeEarliestStart().
Variable Documentation
adcNoiseHandlerState
struct { ... } adcNoiseHandlerState
Referenced by RCL_Handler_ADC_Noise_getNoise().