Radio Control Layer (RCL): Timing API Functions
Timing API Functions
Detailed Description
These functions are useful as part of the API to RCL
Functions
bool RCL_Scheduler_isLater (uint32_t refTime, uint32_t chkTime)
Find if a time instant occurs after another, allowing wrap-around.
int32_t RCL_Scheduler_delta (uint32_t refTime, uint32_t chkTime)
Find the time difference between two times, allowing wrap-around.
static uint32_t RCL_Scheduler_getCurrentTime (void)
Get current time.
RCL_StopType RCL_Scheduler_setSchedStopTime (RCL_SchedulerStopInfo *stopInfo, uint32_t schedStopTime)
Set scheduler stop time.
bool RCL_Scheduler_postEvent (RCL_Command_Handle c, RCL_Events e)
Post event to command handler.
Function Documentation
RCL_Scheduler_isLater()
bool RCL_Scheduler_isLater (uint32_t refTime, uint32_t chkTime)
#include </home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Scheduler.h>
Find if a time instant occurs after another, allowing wrap-around.
Checks if a time is before or after another. In the processing, a time is assumed to be before the reference if it is less than 1/8 of the full timer range (134 seconds) before it; otherwise it is assumed to be in the future. This means that the time presumed to be the latest should always be the second parameter (chkTime)
Parameters
refTime Reference time
chkTime Time to be checked
Returns
true if chkTime comes after refTime. false if chkTime comes before refTime or if they are equal.
Referenced by __attribute__(), RCL_Lite_Command_start(), RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_Scheduler_setStopTimes(), rclSchedulerFindEarliestStopTime(), and rclSchedulerProcessCmdStartStopTime().
RCL_Scheduler_delta()
int32_t RCL_Scheduler_delta (uint32_t refTime, uint32_t chkTime)
#include </home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Scheduler.h>
Find the time difference between two times, allowing wrap-around.
Finds the signed difference between two times, saturated at the maximum signed 32-bit integer value. In the processing, a time is assumed to be before the reference if it is less than 1/8 of the full timer range (134 seconds) before it; otherwise it is assumed to be in the future.
Parameters
refTime Reference time
chkTime Time to be checked
Returns
Time difference (chkTime-refTime) corrected for wrap-around. Saturated at 0x7FFFFFFF (8 min 57 sec).
Referenced by rclSchedulerHwi().
RCL_Scheduler_getCurrentTime()
static uint32_t RCL_Scheduler_getCurrentTime (void) inline static
#include </home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Scheduler.h>
Get current time.
Returns
Current SYSTIM time (0.25 us steps) usable for radio command timing
Referenced by __attribute__(), LRF_enableSynthRefsys(), RCL_Handler_ADC_Noise_getNoise(), RCL_Lite_Command_start(), RCL_Scheduler_setStopTimes(), rclSchedulerFindEarliestStopTime(), rclSchedulerHwi(), and rclSchedulerProcessCmdStartStopTime().
RCL_Scheduler_setSchedStopTime()
RCL_StopType RCL_Scheduler_setSchedStopTime (RCL_SchedulerStopInfo * stopInfo, uint32_t schedStopTime)
#include </home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Scheduler.h>
Set scheduler stop time.
Sets scheduler stop time for the given stop type, finds which of the stop active times comes first, sets selection bits accordingly and reprograms the stop time if it was already programmed.
Parameters
stopInfo Pointer to stop info for the relevant stop type
schedStopTime New scheduler stop time to apply
Returns
Stop type if stop needs to be applied immediately
References RCL_SchedulerStopInfo::cmdStopTime, RCL_Scheduler_setStopTimes(), RCL_SchedulerStopReason_None, RCL_SchedulerStopReason_Scheduling, RCL_SchedulerStopReason_Timeout, RCL_SchedulerStopTimeState_Programmed, RCL_StopType_None, rclSchedulerFindEarliestStopTime(), RCL_SchedulerStopInfo::schedStopEnabled, RCL_SchedulerStopInfo::schedStopTime, RCL_SchedulerStopInfo::stopReason, and RCL_SchedulerState::stopTimeState.
Referenced by __attribute__().
RCL_Scheduler_postEvent()
bool RCL_Scheduler_postEvent (RCL_Command_Handle c, RCL_Events e)
#include </home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/RCL_Scheduler.h>
Post event to command handler.
Parameters
[in] c Command to post event to
[in] e Event(s) to post
Returns
true If command was active and event was posted
false If command was not active
References hal_trigger_command_fsm(), RCL_SchedulerState::postedRclEvents, RCL_CommandStatus_Finished, RCL_CommandStatus_Queued, and RCL_EventSoftwareTriggered.
Referenced by RCL_BLE5_updateFilterList(), RCL_Lite_Command_start(), RCL_Lite_Command_stop(), RCL_MultiBuffer_put(), RCL_TxBuffer_put(), rclSchedulerHwi(), and rclStop().