Radio Control Layer (RCL): ti/drivers/rcl/hal/cc23x0/hal_cc23x0.c File Reference
hal_cc23x0.c File Reference
#include <ti/drivers/dpl/HwiP.h>
#include <ti/drivers/temperature/TemperatureLPF3.h>
#include <ti/devices/DeviceFamily.h>
#include <ti/log/Log.h>
#include <ti/drivers/rcl/hal/hal.h>
Macros
#define RCL_DEFAULT_HFTRACKCTL_RATIO CKMD_HFTRACKCTL_RATIO_REF48M
Enumerations
enum { SYSTIM_CH2_SETUP = 1, SYSTIM_CH2_START = 2, SYSTIM_CH2_STOP = 3 }
Functions
static int hal_power_post_notify_fxn (unsigned int eventType, uintptr_t eventArg, uintptr_t clientArg)
static void hal_cancel_lrfd_systim0 (void)
static void RF_schedHwi (uintptr_t a)
static void RF_dispatchHwi (uintptr_t a)
static void RF_commandHwi (uintptr_t a)
uint32_t hal_get_ifg_reg (void)
void hal_init_fsm (void(*dispatchFsmCb)(void), void(*schedFsmCb)(void), void(*commandFsmCb)(void))
void hal_trigger_command_fsm (void)
void hal_trigger_dispatch_fsm (void)
void hal_trigger_scheduler_fsm (void)
uint32_t hal_get_current_time (void)
void hal_enable_setup_time_irq (void)
void hal_setup_setup_time (uint32_t time)
void hal_setup_start_time (uint32_t time)
void hal_setup_hard_stop_time (uint32_t time)
void hal_enable_hard_stop_time_irq (void)
void hal_setup_graceful_stop_time (uint32_t time)
void hal_enable_graceful_stop_time_irq (void)
void hal_cancel_setup_time (void)
void hal_cancel_start_time (void)
void hal_cancel_hard_stop_time (void)
void hal_cancel_graceful_stop_time (void)
void hal_enable_clk_buffer (void)
void hal_setup_sync_found_cap (void)
HalTimerEvent hal_check_clear_timer_compare (void)
void hal_disable_radio_interrupts (void)
void hal_set_clkctl (uint32_t clkctl)
void hal_power_set_constraint (void)
void hal_power_release_constraint (void)
void hal_power_open (void(*f)(RCL_PowerEvent))
void hal_power_close (void)
void hal_temperature_init (void)
__attribute__ ((weak))
uint32_t hal_get_hfxt_ratio (void)
uint32_t hal_get_hfxt_ratio_default (void)
Variables
Power_NotifyObj powerAwakeStandbyObj
static void(* rclPowerNotify)(RCL_PowerEvent) = NULL
static HwiP_Struct schedHwi
void(* halSchedFsmCb)(void) = NULL
static HwiP_Struct dispatchHwi
void(* halDispatchFsmCb)(void) = NULL
static HwiP_Struct commandHwi
void(* halCommandFsmCb)(void) = NULL
enum { ... } channel2usage = SYSTIM_CH2_SETUP
static bool lrfdClocked = false
Macro Definition Documentation
RCL_DEFAULT_HFTRACKCTL_RATIO
#define RCL_DEFAULT_HFTRACKCTL_RATIO CKMD_HFTRACKCTL_RATIO_REF48M
Referenced by hal_get_hfxt_ratio_default().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SYSTIM_CH2_SETUP
SYSTIM_CH2_START
SYSTIM_CH2_STOP
Function Documentation
hal_power_post_notify_fxn()
static int hal_power_post_notify_fxn (unsigned int eventType, uintptr_t eventArg, uintptr_t clientArg) static
References RCL_POWER_STANDBY_AWAKE, and rclPowerNotify.
Referenced by hal_power_open().
hal_cancel_lrfd_systim0()
static void hal_cancel_lrfd_systim0 (void) static
Referenced by hal_cancel_hard_stop_time(), hal_cancel_setup_time(), and hal_cancel_start_time().
RF_schedHwi()
static void RF_schedHwi (uintptr_t a) static
References halSchedFsmCb.
Referenced by hal_init_fsm().
RF_dispatchHwi()
static void RF_dispatchHwi (uintptr_t a) static
References halDispatchFsmCb.
Referenced by hal_init_fsm().
RF_commandHwi()
static void RF_commandHwi (uintptr_t a) static
References halCommandFsmCb.
Referenced by hal_init_fsm().
hal_get_ifg_reg()
uint32_t hal_get_ifg_reg (void)
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_init_fsm()
void hal_init_fsm (void(*)(void) dispatchFsmCb, void(*)(void) schedFsmCb, void(*)(void) commandFsmCb)
Referenced by RCL_init().
hal_trigger_command_fsm()
void hal_trigger_command_fsm (void)
Referenced by RCL_Scheduler_postEvent().
hal_trigger_dispatch_fsm()
void hal_trigger_dispatch_fsm (void)
Referenced by rclCommandHwi().
hal_trigger_scheduler_fsm()
void hal_trigger_scheduler_fsm (void)
Referenced by RCL_Command_submit(), and rclDispatchHwi().
hal_get_current_time()
uint32_t hal_get_current_time (void)
Referenced by rclSchedulerProcessCmdStartStopTime().
hal_enable_setup_time_irq()
void hal_enable_setup_time_irq (void)
Referenced by rclPowerNotify().
hal_setup_setup_time()
void hal_setup_setup_time (uint32_t time)
Referenced by RCL_Lite_Command_start(), and rclSchedulerHwi().
hal_setup_start_time()
void hal_setup_start_time (uint32_t time)
Referenced by rclSchedulerProcessCmdStartStopTime().
hal_setup_hard_stop_time()
void hal_setup_hard_stop_time (uint32_t time)
Referenced by RCL_Scheduler_setStopTimes().
hal_enable_hard_stop_time_irq()
void hal_enable_hard_stop_time_irq (void)
hal_setup_graceful_stop_time()
void hal_setup_graceful_stop_time (uint32_t time)
Referenced by RCL_Scheduler_setStopTimes().
hal_enable_graceful_stop_time_irq()
void hal_enable_graceful_stop_time_irq (void)
Referenced by RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), and RCL_Handler_Generic_TxRepeat().
hal_cancel_setup_time()
void hal_cancel_setup_time (void)
Referenced by RCL_Lite_Command_start(), and RCL_Lite_CommandHwi().
hal_cancel_start_time()
void hal_cancel_start_time (void)
Referenced by rclCommandHwi().
hal_cancel_hard_stop_time()
void hal_cancel_hard_stop_time (void)
Referenced by RCL_Lite_CommandHwi(), RCL_Scheduler_setStopTimes(), and rclCommandHwi().
hal_cancel_graceful_stop_time()
void hal_cancel_graceful_stop_time (void)
Referenced by RCL_Lite_CommandHwi(), RCL_Scheduler_setStopTimes(), and rclCommandHwi().
hal_enable_clk_buffer()
void hal_enable_clk_buffer (void)
Referenced by RCL_open().
hal_setup_sync_found_cap()
void hal_setup_sync_found_cap (void)
Referenced by RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Rx(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
hal_check_clear_timer_compare()
HalTimerEvent hal_check_clear_timer_compare (void)
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_disable_radio_interrupts()
void hal_disable_radio_interrupts (void)
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_set_clkctl()
void hal_set_clkctl (uint32_t clkctl)
Referenced by LRF_applyNewClockEnable().
hal_power_set_constraint()
void hal_power_set_constraint (void)
Referenced by RCL_AdcNoise_get_samples_blocking(), RCL_AdcNoise_get_samples_callback(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_setSynthPowerState(), and rclCommandHwi().
hal_power_release_constraint()
void hal_power_release_constraint (void)
Referenced by adcNoiseCallback(), RCL_AdcNoise_get_samples_blocking(), RCL_Handler_Generic_setSynthPowerState(), and rclCommandHwi().
hal_power_open()
void hal_power_open (void(*)(RCL_PowerEvent) f)
Referenced by RCL_open().
hal_power_close()
void hal_power_close (void)
Referenced by RCL_close().
hal_temperature_init()
void hal_temperature_init (void)
Referenced by RCL_init().
__attribute__()
void __attribute__ ((weak))
hal_get_hfxt_ratio()
uint32_t hal_get_hfxt_ratio (void)
Referenced by LRF_scaleFreqWithHFXTOffset().
hal_get_hfxt_ratio_default()
uint32_t hal_get_hfxt_ratio_default (void)
Referenced by LRF_scaleFreqWithHFXTOffset().
Variable Documentation
powerAwakeStandbyObj
Power_NotifyObj powerAwakeStandbyObj
Referenced by hal_power_close(), and hal_power_open().
rclPowerNotify
void(* rclPowerNotify) (RCL_PowerEvent) = NULL static
Referenced by hal_power_open(), and hal_power_post_notify_fxn().
schedHwi
HwiP_Struct schedHwi static
Referenced by hal_init_fsm().
halSchedFsmCb
void(* halSchedFsmCb) (void) = NULL
Referenced by hal_init_fsm(), and RF_schedHwi().
dispatchHwi
HwiP_Struct dispatchHwi static
Referenced by hal_init_fsm().
halDispatchFsmCb
void(* halDispatchFsmCb) (void) = NULL
Referenced by hal_init_fsm(), and RF_dispatchHwi().
commandHwi
HwiP_Struct commandHwi static
Referenced by hal_init_fsm().
halCommandFsmCb
void(* halCommandFsmCb) (void) = NULL
Referenced by hal_init_fsm(), and RF_commandHwi().
channel2usage
enum { ... } channel2usage
Referenced by hal_check_clear_timer_compare(), hal_setup_hard_stop_time(), hal_setup_setup_time(), and hal_setup_start_time().
lrfdClocked
bool lrfdClocked = false static