Radio Control Layer (RCL): /home/developer/.conan/data/rcl/7.40.01.01/library-lprf/ga/package/b64f4a52bedd1ff8fbfa2101ba929a67456d11d1/source/ti/drivers/rcl/hal/hal.h File Reference
hal.h File Reference
#include <stdint.h>
Enumerations
enum HalTimerEvent {
HAL_TIMER_EVT_NONE = 0, HAL_TIMER_EVT_SETUP = 1, HAL_TIMER_EVT_START = 2, HAL_TIMER_EVT_GRACEFUL_STOP = 3,
HAL_TIMER_EVT_HARD_STOP = 4
}
enum RCL_PowerEvent { RCL_POWER_STANDBY_AWAKE = 0, RCL_POWER_XTAL_AVAILABLE = 1 }
Functions
void hal_init_fsm (void(*setupFsmCb)(void), void(*schedFsmCb)(void), void(*commandFsmCb)(void))
void hal_trigger_command_fsm (void)
void hal_trigger_dispatch_fsm (void)
void hal_trigger_scheduler_fsm ()
uint32_t hal_get_ifg_reg (void)
uint32_t hal_get_current_time (void)
void hal_enable_setup_time_irq (void)
void hal_setup_setup_time (uint32_t setupTime)
void hal_setup_start_time (uint32_t startTime)
void hal_setup_hard_stop_time (uint32_t stopTime)
void hal_enable_hard_stop_time_irq (void)
void hal_setup_graceful_stop_time (uint32_t stopTime)
void hal_enable_graceful_stop_time_irq (void)
void hal_cancel_setup_time (void)
void hal_cancel_start_time (void)
void hal_cancel_hard_stop_time (void)
void hal_cancel_graceful_stop_time (void)
void hal_disable_radio_interrupts (void)
void hal_temperature_init (void)
int16_t hal_get_temperature (void)
uint32_t hal_get_hfxt_ratio (void)
uint32_t hal_get_hfxt_ratio_default (void)
HalTimerEvent hal_check_clear_timer_compare (void)
void hal_setup_cmd_start_cap (void)
void hal_arm_cmd_start_cap (void)
uint32_t hal_get_cmd_start_cap (void)
void hal_setup_sync_found_cap (void)
void hal_arm_sync_found_cap (void)
uint32_t hal_get_sync_found_cap (void)
void hal_setup_cmd_done_cap (void)
void hal_arm_cmd_done_cap (void)
uint32_t hal_get_cmd_done_cap (void)
void hal_set_clkctl (uint32_t clkctl)
void hal_enable_clk_buffer (void)
void hal_power_set_constraint (void)
void hal_power_release_constraint (void)
void hal_power_open (void(*f)(RCL_PowerEvent))
void hal_power_close (void)
Enumeration Type Documentation
HalTimerEvent
enum HalTimerEvent
Enumerator
HAL_TIMER_EVT_NONE
HAL_TIMER_EVT_SETUP
HAL_TIMER_EVT_START
HAL_TIMER_EVT_GRACEFUL_STOP
HAL_TIMER_EVT_HARD_STOP
RCL_PowerEvent
enum RCL_PowerEvent
Enumerator
RCL_POWER_STANDBY_AWAKE
RCL_POWER_XTAL_AVAILABLE
Function Documentation
hal_init_fsm()
void hal_init_fsm (void(*)(void) setupFsmCb, void(*)(void) schedFsmCb, void(*)(void) commandFsmCb)
References commandHwi, dispatchHwi, halCommandFsmCb, halDispatchFsmCb, halSchedFsmCb, RF_commandHwi(), RF_dispatchHwi(), RF_schedHwi(), and schedHwi.
Referenced by RCL_init().
hal_trigger_command_fsm()
void hal_trigger_command_fsm (void)
Referenced by RCL_Scheduler_postEvent().
hal_trigger_dispatch_fsm()
void hal_trigger_dispatch_fsm (void)
Referenced by rclCommandHwi().
hal_trigger_scheduler_fsm()
void hal_trigger_scheduler_fsm ()
Referenced by RCL_Command_submit(), and rclDispatchHwi().
hal_get_ifg_reg()
uint32_t hal_get_ifg_reg (void)
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_get_current_time()
uint32_t hal_get_current_time (void)
Referenced by rclSchedulerProcessCmdStartStopTime().
hal_enable_setup_time_irq()
void hal_enable_setup_time_irq (void)
Referenced by rclPowerNotify().
hal_setup_setup_time()
void hal_setup_setup_time (uint32_t setupTime)
References channel2usage, and SYSTIM_CH2_SETUP.
Referenced by RCL_Lite_Command_start(), and rclSchedulerHwi().
hal_setup_start_time()
void hal_setup_start_time (uint32_t startTime)
References channel2usage, and SYSTIM_CH2_START.
Referenced by rclSchedulerProcessCmdStartStopTime().
hal_setup_hard_stop_time()
void hal_setup_hard_stop_time (uint32_t stopTime)
References channel2usage, and SYSTIM_CH2_STOP.
Referenced by RCL_Scheduler_setStopTimes().
hal_enable_hard_stop_time_irq()
void hal_enable_hard_stop_time_irq (void)
hal_setup_graceful_stop_time()
void hal_setup_graceful_stop_time (uint32_t stopTime)
Referenced by RCL_Scheduler_setStopTimes().
hal_enable_graceful_stop_time_irq()
void hal_enable_graceful_stop_time_irq (void)
Referenced by RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), and RCL_Handler_Generic_TxRepeat().
hal_cancel_setup_time()
void hal_cancel_setup_time (void)
References hal_cancel_lrfd_systim0().
Referenced by RCL_Lite_Command_start(), and RCL_Lite_CommandHwi().
hal_cancel_start_time()
void hal_cancel_start_time (void)
References hal_cancel_lrfd_systim0().
Referenced by rclCommandHwi().
hal_cancel_hard_stop_time()
void hal_cancel_hard_stop_time (void)
References hal_cancel_lrfd_systim0().
Referenced by RCL_Lite_CommandHwi(), RCL_Scheduler_setStopTimes(), and rclCommandHwi().
hal_cancel_graceful_stop_time()
void hal_cancel_graceful_stop_time (void)
Referenced by RCL_Lite_CommandHwi(), RCL_Scheduler_setStopTimes(), and rclCommandHwi().
hal_disable_radio_interrupts()
void hal_disable_radio_interrupts (void)
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_temperature_init()
void hal_temperature_init (void)
Referenced by RCL_init().
hal_get_temperature()
int16_t hal_get_temperature (void)
Referenced by LRF_programTemperatureCompensatedTxPower(), and LRF_temperatureCompensateTrim().
hal_get_hfxt_ratio()
uint32_t hal_get_hfxt_ratio (void)
References RCL_DEFAULT_HFTRACKCTL_RATIO.
Referenced by LRF_scaleFreqWithHFXTOffset().
hal_get_hfxt_ratio_default()
uint32_t hal_get_hfxt_ratio_default (void)
References RCL_DEFAULT_HFTRACKCTL_RATIO.
Referenced by LRF_scaleFreqWithHFXTOffset().
hal_check_clear_timer_compare()
HalTimerEvent hal_check_clear_timer_compare (void)
References channel2usage, HAL_TIMER_EVT_GRACEFUL_STOP, HAL_TIMER_EVT_HARD_STOP, HAL_TIMER_EVT_NONE, HAL_TIMER_EVT_SETUP, HAL_TIMER_EVT_START, SYSTIM_CH2_SETUP, SYSTIM_CH2_START, and SYSTIM_CH2_STOP.
Referenced by RCL_Lite_CommandHwi(), and rclCommandHwi().
hal_setup_cmd_start_cap()
void hal_setup_cmd_start_cap (void)
hal_arm_cmd_start_cap()
void hal_arm_cmd_start_cap (void)
hal_get_cmd_start_cap()
uint32_t hal_get_cmd_start_cap (void)
hal_setup_sync_found_cap()
void hal_setup_sync_found_cap (void)
Referenced by RCL_Handler_BLE5_adv(), RCL_Handler_BLE5_aux_adv(), RCL_Handler_BLE5_conn(), RCL_Handler_BLE5_genericRx(), RCL_Handler_BLE5_scan_init(), RCL_Handler_Generic_Rx(), RCL_Handler_Nesb_Prx(), and RCL_Handler_Nesb_Ptx().
hal_arm_sync_found_cap()
void hal_arm_sync_found_cap (void)
hal_get_sync_found_cap()
uint32_t hal_get_sync_found_cap (void)
hal_setup_cmd_done_cap()
void hal_setup_cmd_done_cap (void)
hal_arm_cmd_done_cap()
void hal_arm_cmd_done_cap (void)
hal_get_cmd_done_cap()
uint32_t hal_get_cmd_done_cap (void)
hal_set_clkctl()
void hal_set_clkctl (uint32_t clkctl)
Referenced by LRF_applyNewClockEnable().
hal_enable_clk_buffer()
void hal_enable_clk_buffer (void)
Referenced by RCL_open().
hal_power_set_constraint()
void hal_power_set_constraint (void)
Referenced by RCL_AdcNoise_get_samples_blocking(), RCL_AdcNoise_get_samples_callback(), RCL_Handler_Generic_Fs(), RCL_Handler_Generic_setSynthPowerState(), and rclCommandHwi().
hal_power_release_constraint()
void hal_power_release_constraint (void)
Referenced by adcNoiseCallback(), RCL_AdcNoise_get_samples_blocking(), RCL_Handler_Generic_setSynthPowerState(), and rclCommandHwi().
hal_power_open()
void hal_power_open (void(*)(RCL_PowerEvent) f)
References hal_power_post_notify_fxn(), powerAwakeStandbyObj, and rclPowerNotify.
Referenced by RCL_open().
hal_power_close()
void hal_power_close (void)
References powerAwakeStandbyObj.
Referenced by RCL_close().