Radio Control Layer (RCL): ti/drivers/rcl/handlers/generic.h File Reference
generic.h File Reference
#include <stdint.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/LRF.h>
Functions
RCL_Events RCL_Handler_Generic_Fs (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_FsOff (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_Tx (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_TxRepeat (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_TxTest (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_Rx (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Generic_PbeOperation (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Nesb_Ptx (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
RCL_Events RCL_Handler_Nesb_Prx (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
Function Documentation
RCL_Handler_Generic_Fs()
RCL_Events RCL_Handler_Generic_Fs (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References genericHandlerState, hal_power_set_constraint(), LRF_disable(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_programFrequency(), LRF_waitForTopsmReady(), RCL_CommandStatus_Active, RCL_CommandStatus_Finished, RCL_FsType_Tx, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_setSynthPowerState(), and RCL_Scheduler_setStartStopTimeEarliestStart().
RCL_Handler_Generic_FsOff()
RCL_Events RCL_Handler_Generic_FsOff (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References LRF_disable(), LRF_enable(), LRF_EventOpDone, LRF_EventOpError, LRF_waitForTopsmReady(), RCL_CommandStatus_Active, RCL_CommandStatus_Finished, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_setSynthPowerState(), and RCL_Scheduler_setCmdStopTimeNoStartTrigger().
RCL_Handler_Generic_Tx()
RCL_Events RCL_Handler_Generic_Tx (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References genericHandlerState, LRF_disable(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_prepareTxFifo(), LRF_programFrequency(), LRF_programTxPower(), LRF_waitForTopsmReady(), RCL_BufferStateFinished, RCL_CommandStatus_Active, RCL_CommandStatus_Error_MissingTxBuffer, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateSyncWord(), RCL_Handler_Generic_updateTxBuffers(), RCL_ProfilingEvent_PostprocStart, RCL_ProfilingEvent_PreprocStop, RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_TxBuffer_get(), and TxPowerResult_Ok.
RCL_Handler_Generic_TxRepeat()
RCL_Events RCL_Handler_Generic_TxRepeat (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References RCL_SchedulerStopInfo::cmdStopEnabled, genericHandlerState, RCL_SchedulerState::gracefulStopInfo, hal_enable_graceful_stop_time_irq(), LRF_disable(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_getTxFifoWritable(), LRF_prepareTxFifo(), LRF_programFrequency(), LRF_programTxPower(), LRF_waitForTopsmReady(), LRF_writeTxFifoWords(), RCL_Buffer_DataEntry_paddedLen, RCL_CommandStatus_Active, RCL_CommandStatus_Error_MissingTxBuffer, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateSyncWord(), RCL_Scheduler_findStopStatus(), RCL_Scheduler_setNewStartNow(), RCL_Scheduler_setNewStartRelTime(), RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_StopType_Graceful, RCL_StopType_Hard, rclSchedulerState, RCL_SchedulerStopInfo::schedStopEnabled, and TxPowerResult_Ok.
RCL_Handler_Generic_TxTest()
RCL_Events RCL_Handler_Generic_TxTest (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References genericHandlerState, LRF_disable(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_programFrequency(), LRF_programTxPower(), LRF_waitForTopsmReady(), RCL_CMD_GENERIC_WH_MODE_NONE, RCL_CMD_GENERIC_WH_MODE_PRBS15, RCL_CommandStatus_Active, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_HANDLER_GENERIC_PRBS15_POLY, RCL_HANDLER_GENERIC_PRBS32_POLY, RCL_HANDLER_GENERIC_PRBS_INIT, RCL_HANDLER_GENERIC_PRBS_SYNC, RCL_HANDLER_GENERIC_RESTORE_MODCTRL, RCL_HANDLER_GENERIC_RESTORE_NONE, RCL_HANDLER_GENERIC_RESTORE_WHITEN_INIT, RCL_HANDLER_GENERIC_RESTORE_WHITEN_POLY, RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateSyncWord(), RCL_Scheduler_setStartStopTimeEarliestStart(), and TxPowerResult_Ok.
RCL_Handler_Generic_Rx()
RCL_Events RCL_Handler_Generic_Rx (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References RCL_SchedulerState::actualStartTime, genericHandlerState, hal_setup_sync_found_cap(), LRF_disable(), LRF_discardRxFifoWords(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_EventRxNok, LRF_EventRxOk, LRF_peekRxFifo(), LRF_prepareRxFifo(), LRF_programFrequency(), LRF_readRxFifoWords(), LRF_setRxFifoEffSz(), LRF_waitForTopsmReady(), RCL_Buffer_DataEntry_paddedLen, RCL_CommandStatus_Active, RCL_CommandStatus_Error_RxBufferCorruption, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_EventNone, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_initRxStats(), RCL_Handler_Generic_maskEventsByFifoConf(), RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateLongStats(), RCL_Handler_Generic_updateRxCurBufferAndFifo(), RCL_Handler_Generic_updateRxStats(), RCL_Handler_Generic_updateSyncWord(), RCL_MultiBuffer_commitBytes(), RCL_MultiBuffer_getBuffer(), RCL_MultiBuffer_getNextWritableByte(), RCL_ProfilingEvent_PostprocStart, RCL_ProfilingEvent_PreprocStop, RCL_Scheduler_findStopStatus(), RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_StopType_Graceful, and rclSchedulerState.
RCL_Handler_Generic_PbeOperation()
RCL_Events RCL_Handler_Generic_PbeOperation (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References LRF_disable(), LRF_enable(), LRF_EventOpDone, LRF_EventOpError, LRF_waitForTopsmReady(), RCL_CommandStatus_Active, RCL_CommandStatus_Finished, RCL_CommandStatus_Scheduled, RCL_Handler_Generic_findPbeErrorEndStatus(), and RCL_Scheduler_setCmdStopTimeNoStartTrigger().
RCL_Handler_Nesb_Ptx()
RCL_Events RCL_Handler_Nesb_Ptx (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References RCL_SchedulerState::actualStartTime, genericHandlerState, hal_setup_sync_found_cap(), LRF_disable(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_EventRxNok, LRF_EventRxOk, LRF_peekRxFifo(), LRF_prepareRxFifo(), LRF_prepareTxFifo(), LRF_programFrequency(), LRF_programTxPower(), LRF_readRxFifoWords(), LRF_waitForTopsmReady(), RCL_Buffer_DataEntry_paddedLen, RCL_BufferStateFinished, RCL_CommandStatus_Active, RCL_CommandStatus_Error_MissingTxBuffer, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Error_RxBufferCorruption, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_CommandStatus_NoSync, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_maskEventsByFifoConf(), RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateRxCurBufferAndFifo(), RCL_Handler_Generic_updateSyncWord(), RCL_Handler_Generic_updateTxBuffers(), RCL_Handler_Nesb_initStats(), RCL_Handler_Nesb_updateHeader(), RCL_Handler_Nesb_updateLongStats(), RCL_Handler_Nesb_updateStats(), RCL_MultiBuffer_commitBytes(), RCL_MultiBuffer_getBuffer(), RCL_MultiBuffer_getNextWritableByte(), RCL_ProfilingEvent_PostprocStart, RCL_ProfilingEvent_PreprocStop, RCL_Scheduler_setNewStartNow(), RCL_Scheduler_setNewStartRelTime(), RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_TxBuffer_get(), rclSchedulerState, and TxPowerResult_Ok.
RCL_Handler_Nesb_Prx()
RCL_Events RCL_Handler_Nesb_Prx (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References RCL_SchedulerState::actualStartTime, genericHandlerState, hal_setup_sync_found_cap(), LRF_disable(), LRF_discardRxFifoWords(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_EventRxIgnored, LRF_EventRxNok, LRF_EventRxOk, LRF_peekRxFifo(), LRF_prepareRxFifo(), LRF_prepareTxFifo(), LRF_programFrequency(), LRF_programTxPower(), LRF_readRxFifoWords(), LRF_setRxFifoEffSz(), LRF_waitForTopsmReady(), RCL_Buffer_DataEntry_paddedLen, RCL_CommandStatus_Active, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Error_RxBufferCorruption, RCL_CommandStatus_Error_Synth, RCL_CommandStatus_Finished, RCL_EventNone, RCL_Handler_Generic_findPbeErrorEndStatus(), RCL_Handler_Generic_maskEventsByFifoConf(), RCL_Handler_Generic_setSynthPowerState(), RCL_Handler_Generic_updateRxCurBufferAndFifo(), RCL_Handler_Generic_updateSyncWord(), RCL_Handler_Nesb_initStats(), RCL_Handler_Nesb_updateLongStats(), RCL_Handler_Nesb_updateStats(), RCL_MultiBuffer_commitBytes(), RCL_MultiBuffer_getBuffer(), RCL_MultiBuffer_getNextWritableByte(), RCL_ProfilingEvent_PostprocStart, RCL_ProfilingEvent_PreprocStop, RCL_Scheduler_findStopStatus(), RCL_Scheduler_setStartStopTimeEarliestStart(), RCL_StopType_Graceful, rclSchedulerState, and TxPowerResult_Ok.