Radio Control Layer (RCL): ti/drivers/rcl/handlers/adc_noise.h File Reference
adc_noise.h File Reference
#include <stdint.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/LRF.h>
Functions
RCL_Events RCL_Handler_ADC_Noise_getNoise (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
Function Documentation
RCL_Handler_ADC_Noise_getNoise()
RCL_Events RCL_Handler_ADC_Noise_getNoise (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References ADC_NOISE_SAMPLE_PTR, adcNoiseHandlerState, LRF_disableSynthRefsys(), LRF_enableSynthRefsys(), RCL_ADC_NOISE_MAX_NUM_WORDS, RCL_CommandStatus_Active, RCL_CommandStatus_Error_Param, RCL_CommandStatus_Finished, RCL_Handler_Adc_Noise_configureS2R(), RCL_Handler_Adc_Noise_powerDown(), RCL_Handler_Adc_Noise_powerUp(), RCL_Scheduler_getCurrentTime(), RCL_Scheduler_setNewStartAbsTime(), and RCL_Scheduler_setStartStopTimeEarliestStart().