Radio Control Layer (RCL): ti/drivers/rcl/handlers/ble_cs.h File Reference
ble_cs.h File Reference
#include <stdint.h>
#include <ti/drivers/rcl/RCL_Command.h>
#include <ti/drivers/rcl/LRF.h>
Functions
RCL_Events RCL_Handler_BLE_CS (RCL_Command *cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
Function Documentation
RCL_Handler_BLE_CS()
RCL_Events RCL_Handler_BLE_CS (RCL_Command * cmd, LRF_Events lrfEvents, RCL_Events rclEventsIn)
References bleCsHandlerState, LRF_disable(), LRF_disableSynthRefsys(), LRF_enable(), LRF_enableSynthRefsys(), LRF_EventOpDone, LRF_EventOpError, LRF_EventRxfifo, LRF_EventTxCtrlAck, LRF_EventTxfifo, LRF_waitForTopsmReady(), RCL_CommandStatus_Active, RCL_CommandStatus_Finished, RCL_Handler_BLE_CS_configureS2R(), RCL_Handler_BLE_CS_configureTxRxFIFO(), RCL_Handler_BLE_CS_fillTxBuffer(), RCL_Handler_BLE_CS_findPbeErrorEndStatus(), RCL_Handler_BLE_CS_preprocessCommand(), RCL_Handler_BLE_CS_readRxBuffer(), RCL_Handler_BLE_CS_readS2RSamples(), RCL_Handler_BLE_CS_readStatistics(), and RCL_Scheduler_setStartStopTimeEarliestStart().